### ISSUE TITLE
Set Timezone

### ISSUE THREAD

**Issue by skyguide** [jaredstehler/dropwizard-quartz#6]
Hi
Not so much an issue, more of a question..

What is the default timezone for the dropwizard-quartz plugin and is there a way to override it?

Thanks

**Comment by jaredstehler** [comment]
I've added the ability to override the default timezone (which is the system's timezone) in the configuration: https://github.com/jaredstehler/dropwizard-quartz/commit/89576d66a52d9f954a2251134285e9ac3913eda3

Example, to use UTC, or EST: 
```
schedulerConfiguration.setTimezone("UTC");
schedulerConfiguration.setTimezone("America/New_York");
```
