### ISSUE TITLE
Does dropwizard-quartz support quartz cluster?

### ISSUE THREAD

**Issue by hsong1234** [jaredstehler/dropwizard-quartz#8]
It's a question: does dropwizard-quartz support quartz cluster with a jdbc store? Thanks!

**Comment by jaredstehler** [comment]
i believe it should; in theory this library should function as a small shim over the quartz library and should therefore support everything it does. please let me know / PR if it doesn't!

**Comment by antonioberben** [comment]
hi guys, what happened with this topic? 

I am about to integrate this, but if in the end it does not cover cluster mode somehow, it won't satisfy requirements I have got.
